--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DavyCraft648/InputPermission
build-by-default: true
branches:
- master
projects:
  InputPermission:
    path: ""
    libs:
      - src: DavyCraft648/PMInputAPI/PMInputAPI
        version: ^1.0.1
      - src: DavyCraft648/PMServerUI/PMServerUI
        version: ^1.0.2
...
